{% set name = "pyrsr" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrsr-{{ version }}.tar.gz
  sha256: 4f96195a1891bb85bddc146c1190d9ec24c580047326bb24d8c01223f0a97264

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-git
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scipy

test:
  imports:
    - pyrsr
    - pyrsr.rsr
    - pyrsr.sensorspecs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitext.gfz-potsdam.de/geomultisens/pyrsr
  summary: A package providing relative spectral response functions for remote sensing instruments.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
