{% set name = "pyrsr" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrsr-{{ version }}.tar.gz
  sha256: 3a184ea7940feb408d26b89519f1f930142e571d1e38cd5336542e55080e1ad2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-git
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scipy

test:
  imports:
    - pyrsr
    - pyrsr.rsr
    - pyrsr.sensorspecs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/geomultisens/pyrsr
  summary: A package providing relative spectral response functions for remote sensing instruments.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
